@startuml





/' Objects '/

class Cell {
	+distance_squared : float
	+position : v3
}


class Obstacle {
	+Obstacle(v3 position, v3 scaling, Model model, bool enabled, std::string identifier)
	+~Obstacle()
	+model : Model
	+enabled : bool
	+geom : std::shared_ptr<fcl::BVHModel<fcl::OBBf>>
	+identifier : std::string
	+position : v3
	+scaling : v3
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
