@startuml





/' Objects '/

class v3 {
	+Vector3f() {query}
	+operatorVector3() {query}
	+operatorfloat*() {query}
	+v3(float x, float y, float z)
	+v3(fcl::Vector3f v)
	+v3(Vector3 v)
	+v3()
	+v3(float v)
	+operator!=(const v3& other) : bool {query}
	+operator==(const v3& other) : bool {query}
	+volume() : float {query}
	+x : float
	+y : float
	+z : float
	+to_string() : std::string {query}
	+operator*(const v3& other) : v3 {query}
	+operator*(const float& other) : v3 {query}
	+operator*=(const v3& other) : v3
	+operator*=(const float& other) : v3
	+operator+(const v3& other) : v3 {query}
	+operator+(const float& other) : v3 {query}
	+operator+=(const v3& other) : v3
	+operator+=(const float& other) : v3
	+operator-(const v3& other) : v3 {query}
	+operator-(const float& other) : v3 {query}
	+operator-=(const v3& other) : v3
	+operator-=(const float& other) : v3
	+operator/(const v3& other) : v3 {query}
	+operator/(const float& other) : v3 {query}
	+operator/=(const v3& other) : v3
	+operator/=(const float& other) : v3
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
